Unit test
Informasjonsforvaltning/a-front-end-service pull request #9
Opened 2019-12-19 13:08 UTC by rannveigskjerve

Eksempler på enhetstester. (Kontrakt test med codeceptjs er innbakt, men trenger ikke å se så nøye på det nå, mangler typescript)

2019-12-19 13:14 UTC, stigbd approved these changes

2019-12-20 08:03 UTC, azaxarov requested changes

2019-12-20 08:03 UTC, azaxarov commented on jsconfig.json
> +}
Skal denne filen hete "tsconfig.json" i stedet for "jsconfig.json"?

2019-12-20 08:03 UTC, azaxarov commented on src/index.html
> +        <h1>FDK microservices</h1>
index.html skal ikke røres - gjør heller dette i react

2019-12-20 08:03 UTC, azaxarov commented on src/index.tsx
> +  <ReduxProvider store={store}>
Du finner referanse implementasjonen for dette i fdk-admin-gui

2019-12-20 08:03 UTC, azaxarov commented on src/redux/actions/index.ts
> +} from './types';
Ta bort disse action typer og heller se på src/types/comon.d.ts. Der defineres en generisk Action type some kan gjenbrukes og er felles for alle actions

2019-12-20 08:03 UTC, azaxarov commented on src/redux/actions/index.ts
> +    type: ServiceActionTypes.FETCH_SUCCEEDED,
Hvordan exporteres action types? Virker unødvendig å ha ServiceActionTypes foran

2019-12-20 08:03 UTC, azaxarov commented on src/redux/actions/index.ts
> +    payload: serviceDetails
payload er en konvensjon property - ikke assign direkte til payload

2019-12-20 08:03 UTC, azaxarov commented on src/redux/actions/index.ts
> +  return { type: ServiceActionTypes.FETCH_DETAILS_FAILED, error: message };
payload mangler

2019-12-20 08:03 UTC, azaxarov commented on src/redux/actions/types.ts
> +}
Flytt ut til egen fil - se fdk-admin-gui for eksempler

2019-12-20 08:03 UTC, azaxarov commented on src/redux/actions/types.ts
> +  | FetchServiceEndpointSuccededAction;
Hele filen kan erstattes med en type definisjon - se src/types/common.d.ts i fdk-admin-gui

2019-12-20 08:03 UTC, azaxarov commented on src/redux/reducers/index.ts
> +export type RootState = ReturnType<typeof rootReducer>;
Trenger ikke denne

2019-12-20 08:03 UTC, azaxarov commented on src/redux/reducers/index.ts
> +import ServiceEndpointsReducer from './ServiceEndpointReducer';
importer med det navnet du ønsker å bruke

2019-12-20 08:03 UTC, azaxarov commented on tsconfig.json
> +        "./src/**/*.ts"
Skal ikke være nødvendig - alle TS filene er registrert unansett

2019-12-20 08:03 UTC, azaxarov commented on webpack/prod.config.js
> +    { attributes: 'data_test' }
By default attributes with name data-test-id or data-testid (as used in react-testing-library) will be stripped. (https://github.com/coderas/babel-plugin-jsx-remove-data-test-id#define-custom-attribute-names)

2019-12-20 08:03 UTC, azaxarov commented on webpack/prod.config.js
> +  plugins: [
Jeg mistenker at dette er feil sted å ha denne plugin - burde kanskje være i .babelrc?

2019-12-20 08:03 UTC, azaxarov commented on src/redux/reducers/serviceEndpointReducer.ts
> +      return { ...state, ...action.payload };
state skal være immutable - her er den dessverre ikke det

2019-12-20 08:03 UTC, azaxarov commented on package.json
> +    "npm": "^6.13.4",
?

2019-12-20 08:03 UTC, azaxarov commented on package.json
> +    "install": "^0.13.0",
?

2019-12-20 08:09 UTC, rannveigskjerve commented on src/index.html
> +        <h1>FDK microservices</h1>
Oi, den der glemte jeg å fjerne. Takk!

2019-12-20 08:19 UTC, rannveigskjerve commented on src/redux/actions/index.ts
> +    type: ServiceActionTypes.FETCH_SUCCEEDED,
alle action types ligger i enumet ServiceActionTypes som eksporteres. Har lagt det foran for mer sporbarhet i koden (er generelt lite fan av at konstanter hentes ut fra løse lufta).

2019-12-20 08:20 UTC, rannveigskjerve commented on webpack/prod.config.js
> +    { attributes: 'data_test' }
Jupp, men trengte en _ istedet for -

2019-12-20 08:21 UTC, rannveigskjerve commented on webpack/prod.config.js
> +  plugins: [
Skal jo fjerne test-id fra prod, så da må den vel ligge i prod configen?

2019-12-20 08:22 UTC, rannveigskjerve commented on package.json
> +    "npm": "^6.13.4",
Eh, kjørte en oppdtaering av npm, virker som det endte opp lokalt i prosjektet 😕

2020-01-24 09:51 UTC, closed without merging